### ISSUE TITLE
The images are too large first time loading 

### ISSUE THREAD

**Issue by WaleedHamza** [cedricdelpoux/react-responsive-masonry#14] opened 2019-10-23 16:32 UTC
The images are too large in 2 columns when first time loading the site, It will not calculate the browser size and set the number of columns.

**Comment by fmmsilva** [comment] 2020-12-08 16:05
+1

**Comment by salientknight** [comment] 2021-02-25 21:46
+1

**Comment by FrancoLab** [comment] 2022-05-08 17:34
Has anyone found a solution to this?

**Comment by MNITD** [comment] 2024-03-17 17:17
Hey @cedricdelpoux

I suppose the bug was caused by the initial value of `setWidth` that was fixed in https://github.com/cedricdelpoux/react-responsive-masonry/commit/ec3d5147329887f363ec4b14f193235aa8b21c19

Also, I see that you included that fix in the new release [v2.2.0](https://github.com/cedricdelpoux/react-responsive-masonry/commit/bd49831d4d1772fd8844d1bb7aea64f136c48272#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3)

However, it seems that the deployment pipeline is broken because [the NPM pacakge does NOT include the fix](https://www.npmjs.com/package/react-responsive-masonry/v/2.2.0?activeTab=code) (images attached)
My team is still facing this annoying initial single-column rendering on the desktop 

Could you please take a look and redeploy the patch with the actual fix?

<img width="788" alt="image" src="https://github.com/cedricdelpoux/react-responsive-masonry/assets/17023655/47dd9a22-bd47-4f8d-801e-e5db0a6db7cf">
<img width="660" alt="image" src="https://github.com/cedricdelpoux/react-responsive-masonry/assets/17023655/7eb4d00b-1f3b-4905-88d8-02f260aacbc6">

**Comment by cedricdelpoux** [comment] 2024-03-27 15:51
PRs are welcome

**Comment by zvonimirr** [comment] 2024-07-27 15:43
<img width="627" alt="Screenshot 2024-07-27 at 17 43 23" src="https://github.com/user-attachments/assets/952e9d8b-c21e-4f1d-85da-de2e29eaa172">

Seems that it's fixed in 2.3.0

**Closed** 2024-08-02 16:20 UTC
