### ISSUE TITLE
Masonry2` uses `getDerivedStateFromProps` but its initial state is undefined.

### ISSUE THREAD

**Issue by shajal-kumer** [cedricdelpoux/react-responsive-masonry#133] opened 2024-11-29 10:14 UTC
Warning: `Masonry2` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `Masonry2`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape. Error Component Stack

**Comment by ADTC** [comment] 2024-12-04 05:13
Duplicate of #131

**Comment by cedricdelpoux** [comment] 2024-12-04 06:31
Hello, I reverted the commits that caused this issue and published an `v2.5.0`.
Tell me if the regression is gone for you.

Thanks

**Closed by cedricdelpoux** 2024-12-04 06:31 UTC
